language:
  - cpp
os: linux
dist: bionic
jobs:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
            - gcc-9
      compiler: gcc
before_install:
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 90 --slave /usr/bin/g++ g++ /usr/bin/g++-9 --slave /usr/bin/gcov gcov /usr/bin/gcov-9
  - pip install --user cpp-coveralls
script: ./build.sh
after_success:
  - coveralls -b ./build --include src/ --gcov-options '\-lp' --verbose
notifications:
  email: false
